/** All option files that belong to the current behavior have to be included by this file. */

#include "Options/Soccer.h"

#include "Options/GameControl/HandleGameState.h"
#include "Options/GameControl/HandlePenaltyState.h"
#include "Options/GameControl/PlayingState.h"
#include "Options/GameControl/ReadyState.h"

#include "Options/HeadControl/LookForward.h"
#include "Options/HeadControl/LookAround.h"

#include "Options/Output/Activity.h"
#include "Options/Output/Annotation.h"
#include "Options/Output/HeadControlMode.h"

#include "Options/HeadControl/LookBallTarget.h"
#include "Options/HeadControl/TrackBall.h"
#include "Options/HeadControl/SearchBall.h"
#include "Options/HeadControl/TrackBallA.h"
#include "Options/HeadControl/DynamicLook.h"

#include "Options/Output/HeadMotionRequest/SetHeadPanTilt.h"
#include "Options/Output/HeadMotionRequest/SetHeadTarget.h"
#include "Options/Output/HeadMotionRequest/SetHeadTargetOnGround.h"

#include "Options/Output/MotionRequest/InWalkKick.h"
#include "Options/Output/MotionRequest/MakeTurn.h"
#include "Options/Output/MotionRequest/SpecialAction.h"
#include "Options/Output/MotionRequest/Stand.h"
#include "Options/Output/MotionRequest/WalkAtAbsoluteSpeed.h"
#include "Options/Output/MotionRequest/WalkAtRelativeSpeed.h"
#include "Options/Output/MotionRequest/WalkToTarget.h"
#include "Options/Output/MotionRequest/GetUpEngine.h"

#include "Options/Output/PlaySound.h"
#include "Options/Output/Gallina.h"

#include "Options/Roles/Keeper.h"
#include "Options/Roles/aloneKeeper.h"
#include "Options/Roles/Defender.h"
#include "Options/Roles/aloneDefender.h"
#include "Options/Roles/Supporter.h"
#include "Options/Roles/OffensiveSkills.h"
#include "Options/Roles/aloneOffensiveSkills.h"
#include "Options/Roles/Goalie.h"
#include "Options/Roles/Static.h"
#include "Options/Roles/Poste.h"

#include "Options/Skills/GetUp.h"
#include "Options/Skills/ShootAt.h"
#include "Options/Skills/StealBall.h"
#include "Options/Skills/StealBallWith.h"
#include "Options/Skills/StopBall.h"
#include "Options/Skills/Shoot.h"
#include "Options/Skills/DribbleBall.h"
#include "Options/Skills/ChooseRole.h"
#include "Options/Skills/IdealPosition.h"
#include "Options/Tools/ButtonPressedAndReleased.h"
#include "Options/Tools/USBCheck.h"
